name: Deploy on Staging
on:
  push:
    branches: 
      - main
      
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
       - name: Setup SSH
         run: |
           mkdir -p ~/.ssh
           ssh-keyscan 170.64.171.142 >> ~/.ssh/known_hosts
           echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           chmod 600 ~/.ssh/known_hosts
       
       - name: Deploy to Server
         run: |
           ssh -i ~/.ssh/id_rsa root@170.64.171.142 -t  '
             cd bms-cicd/ && git pull &&
             pnpm install && 
             pm2 restart http-server &&
             pm2 restart next-js &&
             pm2 restart web-server
           '